-- | A small spreadsheet formula evaluator, for the cells a workbook does not
-- answer for itself.
--
-- __Read this first: the cached value always wins.__ Excel, LibreOffice and
-- Numbers all write the result of every formula into the file beside it (the
-- @\<v\>@ element), so for a workbook a real spreadsheet program saved,
-- "Cmedit.Xlsx" already shows the right number — computed by the program that
-- owns the format, with full fidelity, including the hundreds of functions
-- this module will never have. Evaluating those cells ourselves could at best
-- reproduce an answer we already have, and at worst quietly contradict it.
--
-- So this module runs on exactly one case: __a formula with no cached value__.
-- That is not a corner case. Workbooks generated by libraries — @openpyxl@,
-- @xlsxwriter@, @pandas.to_excel@ — write the formula and nothing else,
-- because they are not spreadsheet engines either. Before this module those
-- cells showed /blank/, which is the one answer that is certainly wrong. The
-- rule that follows is worth stating plainly: __this never overrides a value
-- the file already gives.__
--
-- __What it does not do.__ No dates or times (@TODAY@ and @NOW@ need a clock,
-- and this module is pure), no number formats (a result is shown the way the
-- file's own cached values are — raw), no array formulas, no defined names, no
-- external workbooks, no volatile or financial functions. A formula this
-- module cannot parse, or that calls a function it does not have, is __left
-- exactly as it was__ — blank — and counted, so the status bar can say how
-- many. Showing nothing is the honest answer to "I do not understand this";
-- showing a number would not be.
--
-- A genuine spreadsheet error is different, and /is/ shown: @#DIV\/0!@ is the
-- answer to @=1\/0@, not a failure to evaluate it.
--
-- Everything here is bounded, since the input is a file we did not write:
-- circular references are detected rather than followed ('maxDepth'), the
-- whole pass has a step budget ('maxSteps'), and the number of formula cells
-- it will attempt is capped ('maxFormulaCells').
--
-- Leaf module: it imports nothing from @Cmedit@, so "Cmedit.Xlsx" and the
-- tests can both use it cycle-free.
module Cmedit.Formula
  ( -- * Values
    Value(..)
  , showNumber
    -- * The formula language
  , Expr(..)
  , parseFormula
  , supportedFunctions
    -- * Evaluating a workbook
  , SheetIn(..)
  , Grid
  , evalWorkbook
  , maxFormulaCells
  , maxSteps
  , maxDepth
  ) where

import Data.Char (isAlpha, isDigit, isSpace, ord, toUpper)
import Data.Foldable (toList)
import Data.List (foldl', sortBy)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as M
import Data.Maybe (fromMaybe, mapMaybe)
import Data.Sequence (Seq)
import qualified Data.Sequence as Seq
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import Numeric (showEFloat, showFFloat)

------------------------------------------------------------------------------
-- Bounds

-- | Most formula cells one workbook will be evaluated for. Past this the rest
-- stay blank and are counted as uncomputed — the same outcome as a formula we
-- do not understand, and reported the same way.
maxFormulaCells :: Int
maxFormulaCells = 50000

-- | Total cell reads across the workbook, counted whether they hit the memo or
-- not. A sheet of whole-column @SUM(A:A)@s is quadratic in the honest case and
-- worse in a hostile one, and the reads inside a range are where that cost
-- lives — which is why this counts /reads/ and not formulas. A cell that runs
-- the budget out shows @#NUM!@ rather than making the editor hang.
maxSteps :: Int
maxSteps = 8000000

-- | Deepest chain of cell-to-cell references followed.
--
-- This is a stack guard, not the cycle detector: a genuine cycle is caught
-- exactly, by set membership on the cells currently being evaluated, so
-- anything that reaches this limit is a chain that is merely very long and is
-- reported as @#NUM!@ rather than mislabelled circular. It is set well past
-- any real workbook's chain because chains /are/ real — a running-total
-- column is one link per row — and because the evaluation order resolves an
-- ascending one at depth 1 anyway.
maxDepth :: Int
maxDepth = 10000

------------------------------------------------------------------------------
-- Values

-- | A cell's value. 'VBlank' is a distinct thing from an empty string: it is
-- zero in arithmetic, empty in text, and false for @ISBLANK@.
data Value
  = VNum  !Double
  | VText !Text
  | VBool !Bool
  | VErr  !Text     -- ^ An Excel error value (@#DIV\/0!@, @#VALUE!@, …).
  | VBlank
  deriving (Eq, Show)

errValue, errNum, errDiv0, errRef, errName, errNA, errCycle :: Value
errValue = VErr "#VALUE!"
errNum   = VErr "#NUM!"
errDiv0  = VErr "#DIV/0!"
errRef   = VErr "#REF!"
errName  = VErr "#NAME?"
errNA    = VErr "#N/A"
-- Not one of Excel's: Excel resolves a circular reference to 0 and warns in
-- its status bar, which a terminal reader has no way to do. Saying so in the
-- cell is the honest equivalent.
errCycle = VErr "#CYCLE!"

-- | Render a number the way the file's own cached values are written: plainly,
-- with no thousands separators and no number format applied, because none is
-- applied to the values we read either.
showNumber :: Double -> Text
showNumber d
  | isNaN d || isInfinite d = "#NUM!"
  | d == 0 = "0"
  | isInt && ad < 1e15 = T.pack (show (round d :: Integer))
  | ad >= 1e15 || ad < 1e-10 = T.pack (showEFloat (Just 6) d "")
  | otherwise = trimZeros (T.pack (showFFloat (Just 10) d ""))
  where
    ad = abs d
    isInt = d == fromIntegral (round d :: Integer)
    trimZeros t
      | T.any (== '.') t = let t' = T.dropWhileEnd (== '0') t
                           in if "." `T.isSuffixOf` t' then T.init t' else t'
      | otherwise = t

-- | A value as text, for display and for the @&@ operator.
asText :: Value -> Text
asText v = case v of
  VNum n  -> showNumber n
  VText t -> t
  VBool b -> if b then "TRUE" else "FALSE"
  VErr e  -> e
  VBlank  -> T.empty

-- | A value in a numeric context. Text is parsed (Excel coerces @"3"@), a
-- blank is zero, an error propagates.
asNum :: Value -> Either Value Double
asNum v = case v of
  VNum n  -> Right n
  VBool b -> Right (if b then 1 else 0)
  VBlank  -> Right 0
  VErr _  -> Left v
  VText t -> maybe (Left errValue) Right (readNumber t)

asBool :: Value -> Either Value Bool
asBool v = case v of
  VBool b -> Right b
  VNum n  -> Right (n /= 0)
  VBlank  -> Right False
  VErr _  -> Left v
  VText t -> case T.toUpper (T.strip t) of
               "TRUE"  -> Right True
               "FALSE" -> Right False
               _       -> Left errValue

-- Parse a number the way a cell's text would be read: optional sign, digits,
-- decimal point, exponent. Deliberately strict — "3 apples" is not 3.
readNumber :: Text -> Maybe Double
readNumber t0
  | T.null t = Nothing
  | otherwise = case reads (fixup (T.unpack t)) :: [(Double, String)] of
      [(d, rest)] | all isSpace rest -> Just d
      _ -> Nothing
  where
    t = T.strip t0
    -- Haskell's reader wants a digit either side of the point and no leading
    -- '+'; spreadsheets write ".5" and "+3" freely.
    fixup s = case s of
      ('+' : r)       -> fixup r
      ('.' : r)       -> '0' : '.' : r
      ('-' : '.' : r) -> '-' : '0' : '.' : r
      _               -> case break (== '.') s of
                           (a, '.' : b) | null b || not (isDigit (head b)) -> a ++ ".0"
                           _ -> s

------------------------------------------------------------------------------
-- The formula language

-- | A parsed formula. Cell references carry an optional sheet name; a
-- reference with no sheet means the one the formula is on.
data Expr
  = ENum !Double
  | EStr !Text
  | EBool !Bool
  | ELitErr !Text                       -- ^ An error typed into the formula (@#N\/A@).
  | ERef !(Maybe Text) !Int !Int        -- ^ sheet, column, row (both 0-based).
  | EArea !(Maybe Text) !Int !Int !Int !Int
    -- ^ sheet, and the inclusive corners @c0 r0 c1 r1@. An open end
    -- (@'maxBound'@) is a whole-column @A:A@ or whole-row @1:1@ reference,
    -- clamped to the sheet when it is read.
  | ENeg !Expr
  | EPercent !Expr
  | EBin !Text !Expr !Expr
  | ECall !Text ![Expr]
  deriving (Eq, Show)

-- | Parse a formula's source (with or without a leading @=@).
--
-- 'Nothing' means "this reader does not understand this", which the caller
-- turns into a cell left exactly as it was. That covers a syntax we do not
-- model (array constants, defined names, structured table references) as well
-- as a genuinely malformed file, and both deserve the same answer: silence.
parseFormula :: Text -> Maybe Expr
parseFormula src0 = case pExpr (lexer src) of
  Just (e, []) | knownCalls e -> Just e
  _                           -> Nothing
  where
    src = T.dropWhile (== '=') (T.strip src0)
    -- A function we do not have is checked up front rather than during
    -- evaluation, so "we cannot compute this" is one answer given once and
    -- never half a result.
    knownCalls e = case e of
      ECall f as -> T.toUpper f `elem` supportedFunctions && all knownCalls as
      ENeg a     -> knownCalls a
      EPercent a -> knownCalls a
      EBin _ a b -> knownCalls a && knownCalls b
      _          -> True

------------------------------------------------------------------------------
-- Lexing

data Tok
  = TNum !Double
  | TStr !Text
  | TName !Text          -- ^ A bare name: a function, a cell reference, TRUE…
  | TSheetName !Text !Text  -- ^ @Sheet1!A1@ — sheet and the name after the @!@.
  | TErrLit !Text
  | TOp !Text
  | TOpen | TClose | TComma | TColon
  deriving (Eq, Show)

lexer :: Text -> [Tok]
lexer t0 = go (T.dropWhile isSpace t0)
  where
    go t = case T.uncons t of
      Nothing -> []
      Just (c, r)
        | isSpace c -> go (T.dropWhile isSpace t)
        | c == '"'  -> let (s, r') = quoted r in TStr s : go r'
        | c == '\'' -> sheetQuoted r
        | c == '('  -> TOpen : go r
        | c == ')'  -> TClose : go r
        | c == ','  -> TComma : go r
        | c == ';'  -> TComma : go r          -- some locales' argument separator
        | c == ':'  -> TColon : go r
        | c == '#'  -> let (e, r') = T.span (\x -> isAlpha x || x `elem` ("/0!?" :: String)) t
                       in if T.null e then go r else TErrLit (T.toUpper e) : go r'
        | isDigit c -> number t
        | c == '.', maybe False isDigit (fmap fst (T.uncons r)) -> number t
        | isNameStart c -> name t
        | otherwise -> operator t

    quoted s = let (a, r) = T.break (== '"') s
               in case T.uncons r of
                    Just ('"', r') -> case T.uncons r' of
                      Just ('"', r'') -> let (b, r3) = quoted r'' in (a <> "\"" <> b, r3)
                      _               -> (a, r')
                    _ -> (a, T.empty)

    -- 'My Sheet'!A1 — the quoted form, which any sheet name with a space in it
    -- has to use.
    sheetQuoted s =
      let (nm, r) = T.break (== '\'') s
          r1 = T.drop 1 r
      in case T.uncons r1 of
           Just ('!', r2) -> let (n, r3) = T.span isNameChar r2
                             in TSheetName nm n : go r3
           _              -> go r1

    number t = let (ds, r) = T.span (\c -> isDigit c || c == '.') t
                   (ex, r') = expPart r
               in case readNumber (ds <> ex) of
                    Just d  -> TNum d : go r'
                    Nothing -> go r'
    expPart t = case T.uncons t of
      Just (e, r) | e == 'e' || e == 'E' ->
        let (sgn, r1) = case T.uncons r of
                          Just (s, rr) | s == '+' || s == '-' -> (T.singleton s, rr)
                          _ -> (T.empty, r)
            (ds, r2) = T.span isDigit r1
        in if T.null ds then (T.empty, t) else (T.cons 'e' (sgn <> ds), r2)
      _ -> (T.empty, t)

    name t = let (n, r) = T.span isNameChar t
             in case T.uncons r of
                  Just ('!', r') -> let (n2, r2) = T.span isNameChar r'
                                    in TSheetName n n2 : go r2
                  _ -> TName n : go r

    operator t = case [ o | o <- twoCharOps, o `T.isPrefixOf` t ] of
      (o : _) -> TOp o : go (T.drop 2 t)
      []      -> case T.uncons t of
        Just (c, r) | c `elem` ("+-*/^&=<>%" :: String) -> TOp (T.singleton c) : go r
                    | otherwise -> go r      -- a byte we have no meaning for
        Nothing -> []

    twoCharOps = ["<=", ">=", "<>"]
    isNameStart c = isAlpha c || c == '_' || c == '$'
    isNameChar c = isAlpha c || isDigit c || c `elem` ("_.$" :: String)

------------------------------------------------------------------------------
-- Parsing
--
-- Recursive descent over Excel's precedence: comparison binds loosest, then
-- concatenation, then +/-, then */, then ^, then unary minus and the postfix
-- percent. Ranges are handled where references are read, since ':' binds
-- tighter than everything.

type P a = [Tok] -> Maybe (a, [Tok])

pExpr :: P Expr
pExpr = pCompare

pCompare :: P Expr
pCompare = chain ["=", "<>", "<=", ">=", "<", ">"] pConcat

pConcat :: P Expr
pConcat = chain ["&"] pAdd

pAdd :: P Expr
pAdd = chain ["+", "-"] pMul

pMul :: P Expr
pMul = chain ["*", "/"] pPow

-- Exponentiation is left-associative in Excel (2^3^2 is 64, not 512).
pPow :: P Expr
pPow = chain ["^"] pUnary

chain :: [Text] -> P Expr -> P Expr
chain ops sub ts = do
  (l, ts1) <- sub ts
  go l ts1
  where
    go l (TOp o : rest) | o `elem` ops = do
      (r, rest') <- sub rest
      go (EBin o l r) rest'
    go l rest = Just (l, rest)

pUnary :: P Expr
pUnary (TOp "-" : ts) = fmap (\(e, r) -> (ENeg e, r)) (pUnary ts)
pUnary (TOp "+" : ts) = pUnary ts
pUnary ts = do
  (e, ts1) <- pPostfix ts
  Just (e, ts1)

pPostfix :: P Expr
pPostfix ts = do
  (e, ts1) <- pAtom ts
  Just (percents e ts1)
  where
    percents e (TOp "%" : r) = percents (EPercent e) r
    percents e r             = (e, r)

pAtom :: P Expr
pAtom ts = case ts of
  -- A whole-row range is written @1:1@, and a bare row number lexes as a
  -- number rather than a name — so it has to be recognised before the literal
  -- case below swallows it.
  (TNum d : TColon : rest) | Just n <- rowTok d -> refOrConst Nothing n (TColon : rest)
  (TNum d : r)    -> Just (ENum d, r)
  (TStr s : r)    -> Just (EStr s, r)
  (TErrLit e : r) -> Just (ELitErr e, r)
  (TOpen : r)     -> do (e, r1) <- pExpr r
                        case r1 of (TClose : r2) -> Just (e, r2); _ -> Nothing
  (TName n : TOpen : r) -> do (as, r1) <- pArgs r
                              Just (ECall n as, r1)
  (TName n : r)   -> refOrConst Nothing n r
  (TSheetName sh n : r) -> refOrConst (Just sh) n r
  _ -> Nothing
  where
    refOrConst sh n r = case T.toUpper n of
      "TRUE"  | sh == Nothing -> Just (EBool True, r)
      "FALSE" | sh == Nothing -> Just (EBool False, r)
      _ -> do
        a <- cellRef n
        case r of
          -- A range: the second half may name its own sheet in a malformed
          -- file; the first one's wins, as everywhere.
          (TColon : TName n2 : r2)        -> mkArea sh a n2 r2
          (TColon : TSheetName _ n2 : r2) -> mkArea sh a n2 r2
          (TColon : TNum d : r2) | Just n2 <- rowTok d -> mkArea sh a n2 r2
          -- A half-reference outside a range is not a cell: @=A@ is not valid
          -- Excel, and letting it through would silently read a blank where a
          -- short defined name (@VAT@, @Tax@) was meant.
          _ | uncurry max a == maxBound -> Nothing
            | otherwise -> Just (uncurry (ERef sh) a, r)
    -- @A:A@ and @1:1@ are open at *both* ends of the axis they name, not just
    -- the far one: taking the recorded 'maxBound' as the start would give an
    -- empty range, which reads on screen as a zero.
    mkArea sh (c0, r0) n2 rest = do
      (c1, r1) <- cellRef n2
      let openRow = r0 == maxBound || r1 == maxBound
          openCol = c0 == maxBound || c1 == maxBound
          (rr0, rr1) | openRow   = (0, maxBound)
                     | otherwise = (min r0 r1, max r0 r1)
          (cc0, cc1) | openCol   = (0, maxBound)
                     | otherwise = (min c0 c1, max c0 c1)
      Just (EArea sh cc0 rr0 cc1 rr1, rest)

-- A row number, as the text half of @1:1@ would have been had it lexed as a
-- name. Whole numbers only, and within a sheet's plausible height.
rowTok :: Double -> Maybe Text
rowTok d
  | d >= 1, d < 1e9, d == fromIntegral n = Just (T.pack (show n))
  | otherwise = Nothing
  where n = round d :: Integer

pArgs :: P [Expr]
pArgs (TClose : r) = Just ([], r)
pArgs ts = go ts
  where
    go t = do
      (e, t1) <- pExpr t
      case t1 of
        (TComma : t2) -> do (es, t3) <- go t2; Just (e : es, t3)
        (TClose : t2) -> Just ([e], t2)
        _             -> Nothing

-- | An A1-style reference to 0-based @(column, row)@, dollar signs ignored
-- (we never move a formula, so absolute and relative are the same thing here).
-- A column with no row (@A@) or a row with no column (@1@) is the open end of
-- a whole-column or whole-row range.
cellRef :: Text -> Maybe (Int, Int)
cellRef raw
  | T.null letters && T.null digits = Nothing
  | T.length letters > 3            = Nothing
  | T.null digits                   = Just (colNum letters, maxBound)
  | T.null letters                  = fmap (\r -> (maxBound, r)) (rowNum digits)
  | not (T.null rest)               = Nothing
  | otherwise                       = fmap (\r -> (colNum letters, r)) (rowNum digits)
  where
    t       = T.filter (/= '$') raw
    letters = T.takeWhile isAlpha (T.map toUpper t)
    afterL  = T.drop (T.length letters) t
    digits  = T.takeWhile isDigit afterL
    rest    = T.drop (T.length digits) afterL
    colNum  = subtract 1 . T.foldl' (\ !a c -> a * 26 + (ord c - ord 'A' + 1)) 0
    rowNum d | T.length d > 8 = Nothing
             | otherwise = let n = T.foldl' (\ !a c -> a * 10 + (ord c - ord '0')) 0 d
                           in if n < 1 then Nothing else Just (n - 1)

------------------------------------------------------------------------------
-- Evaluating a workbook

-- | A grid of already-displayed cell text, as "Cmedit.Xlsx" reads it.
type Grid = Seq (Seq Text)

-- | One sheet's input to the pass: what it already shows, plus the formulas
-- that came with no cached value.
data SheetIn = SheetIn
  { siName     :: !Text
  , siGrid     :: !Grid
  , siFormulas :: !(Map (Int, Int) Text)   -- ^ @(row, column)@ → formula source.
  }

-- Cell coordinates across the workbook.
type Key = (Int, Int, Int)   -- (sheet index, row, column)

data Env = Env
  { envGrids  :: !(Seq Grid)
  , envByName :: !(Map Text Int)          -- ^ Lower-cased sheet name → index.
  , envForms  :: !(Map Key Expr)
  }

-- Where evaluation currently is: which cell's formula is being evaluated (an
-- unqualified reference means that cell's sheet), which cells are open above
-- it, and how deep. A 'Set' rather than a list because a running-total column
-- is a chain thousands deep, and a linear membership test down it on every
-- cell read is quadratic in the length of the chain.
data Ctx = Ctx
  { ctxHere  :: !(Maybe Key)
  , ctxOpen  :: !(Set Key)
  , ctxDepth :: !Int
  }

ctx0 :: Ctx
ctx0 = Ctx Nothing Set.empty 0

data St = St
  { stCache :: !(Map Key Value)
  , stSteps :: !Int
  }

-- | Fill in every formula cell that came with no cached value.
--
-- Returns the completed grids, how many cells were computed, and how many were
-- left alone because this reader could not parse them or does not have the
-- function they call. The two counts are what the status bar reports: the
-- second is the honest half.
evalWorkbook :: [SheetIn] -> ([(Text, Grid)], Int, Int)
evalWorkbook sheets = (zipWith fill [0 ..] sheets, computed, unsupported)
  where
    grids = Seq.fromList (map siGrid sheets)
    env = Env
      { envGrids  = grids
      , envByName = M.fromList (zip (map (T.toLower . siName) sheets) [0 ..])
      , envForms  = parsed
      }
    -- Parse everything first: a formula we cannot read is not attempted, and
    -- is not a reference anything else can resolve through either.
    (parsed, unsupported) =
      let cells = [ ((si, r, c), src)
                  | (si, sh) <- zip [0 ..] sheets
                  , ((r, c), src) <- M.toList (siFormulas sh) ]
          taken = take maxFormulaCells cells
          ok    = [ (k, e) | (k, src) <- taken, Just e <- [parseFormula src] ]
      in (M.fromList ok, length cells - length ok)

    -- In key order, which is row-major per sheet. Not required for
    -- correctness (anything unresolved is evaluated on demand) but it means
    -- the common downward-accumulating chain is already cached by the time
    -- each link asks for the one above it, so it resolves at depth 1.
    results = fst (foldl' step (M.empty, St M.empty 0) (M.keys parsed))
      where step (acc, st) k =
              let (v, st') = evalCell env ctx0 k st
              in (M.insert k v acc, st')

    computed = M.size results

    fill si sh = (siName sh, foldl' put (siGrid sh) (M.toList (siFormulas sh)))
      where
        put g ((r, c), _) = case M.lookup (si, r, c) results of
          Nothing -> g
          Just v  -> setCell r c (asText v) g

-- Write one computed value into the grid.
--
-- 'Seq.adjust'' rather than 'Seq.update', at both levels: @update@ stores
-- @const x@ applied to the value it replaced, so folding it over twenty
-- thousand formula cells builds twenty thousand nested thunks over the grid
-- and nothing is released until the renderer forces them. This is the same
-- trap 'Cmedit.TextBuffer' documents for buffer lines.
setCell :: Int -> Int -> Text -> Grid -> Grid
setCell r c t g = case Seq.lookup r g of
  Nothing  -> g
  Just row | c < 0 || c >= Seq.length row -> g
           | otherwise -> Seq.adjust' (const (Seq.adjust' (const t) c row)) r g

-- | Evaluate one cell, memoised, with the set of cells currently being
-- evaluated as the cycle guard.
evalCell :: Env -> Ctx -> Key -> St -> (Value, St)
evalCell env ctx k st
  | stSteps st >= maxSteps = (errNum, st)
  | otherwise = case M.lookup k (stCache st1) of
      Just v  -> (v, st1)
      Nothing
        | Set.member k (ctxOpen ctx) -> (errCycle, st1)
        | ctxDepth ctx >= maxDepth   -> (errNum, st1)
        | otherwise -> case M.lookup k (envForms env) of
            Nothing -> (literalAt env k, st1)
            Just e  ->
              let ctx' = Ctx { ctxHere  = Just k
                             , ctxOpen  = Set.insert k (ctxOpen ctx)
                             , ctxDepth = ctxDepth ctx + 1 }
                  (v, st2) = evalExpr env ctx' e st1
              in (v, st2 { stCache = M.insert k v (stCache st2) })
  where st1 = st { stSteps = stSteps st + 1 }

-- The value a cell has without being computed: whatever text it already
-- shows, read as a number where it looks like one (the grid is text, because
-- that is what the view draws).
literalAt :: Env -> Key -> Value
literalAt env (si, r, c) = case Seq.lookup si (envGrids env) >>= Seq.lookup r >>= Seq.lookup c of
  Nothing -> VBlank
  Just t
    | T.null t -> VBlank
    | Just d <- readNumber t -> VNum d
    | T.toUpper t == "TRUE"  -> VBool True
    | T.toUpper t == "FALSE" -> VBool False
    | otherwise -> VText t

evalExpr :: Env -> Ctx -> Expr -> St -> (Value, St)
evalExpr env ctx expr st0 = case expr of
  ENum d    -> (VNum d, st0)
  EStr s    -> (VText s, st0)
  EBool b   -> (VBool b, st0)
  ELitErr e -> (VErr e, st0)

  ERef sh c r -> case resolveSheet env ctx sh of
    Nothing -> (errRef, st0)
    Just si -> evalCell env ctx (si, r, c) st0

  -- An area used where a single value is wanted is an error; the functions
  -- that take ranges read them through 'valuesOf' instead.
  EArea{} -> (errValue, st0)

  ENeg e -> num1 e negate
  EPercent e -> num1 e (/ 100)

  EBin op a b ->
    let (va, st1) = evalExpr env ctx a st0
        (vb, st2) = evalExpr env ctx b st1
    in (binop op va vb, st2)

  ECall f as -> callFn env ctx (T.toUpper f) as st0
  where
    num1 e f = let (v, st1) = evalExpr env ctx e st0
               in (either id (VNum . f) (asNum v), st1)

resolveSheet :: Env -> Ctx -> Maybe Text -> Maybe Int
resolveSheet _   ctx Nothing   = case ctxHere ctx of Just (si, _, _) -> Just si; Nothing -> Just 0
resolveSheet env _   (Just nm) = M.lookup (T.toLower nm) (envByName env)

binop :: Text -> Value -> Value -> Value
binop op a b = case op of
  "&" -> case (a, b) of
           (VErr _, _) -> a
           (_, VErr _) -> b
           _           -> VText (asText a <> asText b)
  "=" -> cmp (== EQ)
  "<>"-> cmp (/= EQ)
  "<" -> cmp (== LT)
  ">" -> cmp (== GT)
  "<="-> cmp (/= GT)
  ">="-> cmp (/= LT)
  _   -> arith
  where
    arith = case (asNum a, asNum b) of
      (Left e, _) -> e
      (_, Left e) -> e
      (Right x, Right y) -> case op of
        "+" -> VNum (x + y)
        "-" -> VNum (x - y)
        "*" -> VNum (x * y)
        "/" -> if y == 0 then errDiv0 else VNum (x / y)
        "^" -> let r = x ** y in if isNaN r || isInfinite r then errNum else VNum r
        _   -> errValue
    -- Comparison follows Excel's type ordering: numbers sort before text
    -- before booleans, and text compares case-insensitively.
    cmp p = case (a, b) of
      (VErr _, _) -> a
      (_, VErr _) -> b
      _           -> VBool (p (compareValues a b))

compareValues :: Value -> Value -> Ordering
compareValues a b = case (norm a, norm b) of
  (VNum x, VNum y)   -> compare x y
  (VText x, VText y) -> compare (T.toLower x) (T.toLower y)
  (VBool x, VBool y) -> compare x y
  (x, y)             -> compare (rank x) (rank y)
  where
    -- A blank compares as the zero/empty of whatever it is up against.
    norm VBlank = case (a, b) of
      (VBlank, VText _) -> VText T.empty
      (VText _, VBlank) -> VText T.empty
      (VBlank, VBool _) -> VBool False
      (VBool _, VBlank) -> VBool False
      _                 -> VNum 0
    norm v = v
    rank v = case v of VNum _ -> 0 :: Int; VText _ -> 1; VBool _ -> 2; _ -> 3

------------------------------------------------------------------------------
-- Functions
--
-- The set is chosen by what actually appears in generated workbooks: the
-- aggregates, the conditional, the rounding family, the text handling and one
-- lookup. Each is small; what keeps them honest is that anything /not/ here
-- makes the whole formula unsupported up front ('parseFormula'), so a cell is
-- never half-computed.

-- | Every function name this module implements.
supportedFunctions :: [Text]
supportedFunctions =
  [ "SUM", "AVERAGE", "MIN", "MAX", "COUNT", "COUNTA", "COUNTBLANK", "PRODUCT"
  , "MEDIAN", "SUMPRODUCT"
  , "IF", "IFERROR", "IFNA", "AND", "OR", "NOT", "TRUE", "FALSE"
  , "SUMIF", "COUNTIF", "AVERAGEIF"
  , "ABS", "ROUND", "ROUNDUP", "ROUNDDOWN", "INT", "TRUNC", "MOD", "POWER"
  , "SQRT", "SIGN", "EXP", "LN", "LOG10", "PI", "CEILING", "FLOOR"
  , "LEN", "LEFT", "RIGHT", "MID", "UPPER", "LOWER", "TRIM", "CONCATENATE"
  , "CONCAT", "REPT", "SUBSTITUTE", "TEXTJOIN"
  , "VLOOKUP", "HLOOKUP", "INDEX", "MATCH"
  , "ISBLANK", "ISNUMBER", "ISTEXT", "ISERROR", "N"
  ]

-- Evaluate a function's arguments, keeping ranges as ranges (the aggregates
-- need every cell) and everything else as a single value.
data Arg = AVal !Value | ARange ![Value]

callFn :: Env -> Ctx -> Text -> [Expr] -> St -> (Value, St)
callFn env ctx f as st0 = case f of
  -- The short-circuiting ones evaluate their arguments themselves.
  "IF" -> case as of
    (c : t : rest) ->
      let (cv, st1) = evalExpr env ctx c st0
      in case asBool cv of
           Left e      -> (e, st1)
           Right True  -> evalExpr env ctx t st1
           Right False -> case rest of
             (e : _) -> evalExpr env ctx e st1
             []      -> (VBool False, st1)
    _ -> (errValue, st0)
  "IFERROR" -> guardErr (\v -> case v of VErr _ -> True; _ -> False)
  "IFNA"    -> guardErr (== errNA)
  _ -> let (args, st1) = evalArgs env ctx as st0
       in (applyFn f args, st1)
  where
    guardErr isBad = case as of
      [a, b] -> let (v, st1) = evalExpr env ctx a st0
                in if isBad v then evalExpr env ctx b st1 else (v, st1)
      _      -> (errValue, st0)

evalArgs :: Env -> Ctx -> [Expr] -> St -> ([Arg], St)
evalArgs env ctx as st0 = go as st0
  where
    go [] st = ([], st)
    go (e : rest) st =
      let (a, st1) = evalArg env ctx e st
          (bs, st2) = go rest st1
      in (a : bs, st2)

evalArg :: Env -> Ctx -> Expr -> St -> (Arg, St)
evalArg env ctx e st = case e of
  EArea sh c0 r0 c1 r1 -> case resolveSheet env ctx sh of
    Nothing -> (AVal errRef, st)
    Just si ->
      let g  = fromMaybe Seq.empty (Seq.lookup si (envGrids env))
          nr = Seq.length g
          nc = maximum (0 : map Seq.length (toList g))
          rr = [max 0 r0 .. min (nr - 1) (if r1 == maxBound then nr - 1 else r1)]
          cc = [max 0 c0 .. min (nc - 1) (if c1 == maxBound then nc - 1 else c1)]
          step (vs, s) (r, c) = let (v, s') = evalCell env ctx (si, r, c) s in (v : vs, s')
          (vals, st') = foldl' step ([], st) [ (r, c) | r <- rr, c <- cc ]
      in (ARange (reverse vals), st')
  _ -> let (v, st') = evalExpr env ctx e st in (AVal v, st')

-- Every value an argument stands for (a range flattens, a scalar is itself).
argVals :: Arg -> [Value]
argVals (AVal v)   = [v]
argVals (ARange vs) = vs

-- Numbers for an aggregate. Excel's rule: text and blanks inside a *range* are
-- ignored, but a scalar argument is coerced — @SUM(A1:A9)@ skips a stray label,
-- @SUM("3")@ is 3.
aggNums :: [Arg] -> Either Value [Double]
aggNums = foldr step (Right [])
  where
    step a acc = case acc of
      Left e -> Left e
      Right ns -> case a of
        AVal v -> case asNum v of
          Left e  -> Left e
          Right d -> Right (d : ns)
        ARange vs -> case firstErr vs of
          Just e  -> Left e
          Nothing -> Right ([ d | VNum d <- vs ] ++ ns)
    firstErr vs = case [ v | v@(VErr _) <- vs ] of (e : _) -> Just e; [] -> Nothing

applyFn :: Text -> [Arg] -> Value
applyFn f args = case f of
  "SUM"     -> agg sum
  "PRODUCT" -> agg product
  "AVERAGE" -> aggNE (\ns -> sum ns / fromIntegral (length ns))
  "MIN"     -> aggNE minimum
  "MAX"     -> aggNE maximum
  "MEDIAN"  -> aggNE median
  "COUNT"   -> VNum (fromIntegral (length [ () | v <- vals, isNumV v ]))
  "COUNTA"  -> VNum (fromIntegral (length [ () | v <- vals, v /= VBlank ]))
  "COUNTBLANK" -> VNum (fromIntegral (length [ () | v <- vals, v == VBlank ]))
  "SUMPRODUCT" -> case map (mapMaybe numOf . argVals) args of
    (xs : rest) | not (null rest)
      , all ((== length xs) . length) rest ->
          VNum (sum (foldl' (zipWith (*)) xs rest))
    [xs] -> VNum (sum xs)
    _    -> errValue

  "TRUE"  -> VBool True
  "FALSE" -> VBool False
  "AND"   -> logical and
  "OR"    -> logical or
  "NOT"   -> one1 (\v -> either id (VBool . not) (asBool v))

  "SUMIF"     -> condAgg (\ms -> VNum (sum ms))
  "AVERAGEIF" -> condAgg (\ms -> if null ms then errDiv0
                                   else VNum (sum ms / fromIntegral (length ms)))
  "COUNTIF" -> case args of
    [ARange rs, AVal c] -> VNum (fromIntegral (length (filter (matches c) rs)))
    [AVal r, AVal c]    -> VNum (if matches c r then 1 else 0)
    _                   -> errValue

  "ABS"   -> num1 abs
  "INT"   -> num1 (fromIntegral . (floor :: Double -> Integer))
  "TRUNC" -> num1 (fromIntegral . (truncate :: Double -> Integer))
  "SIGN"  -> num1 (\x -> if x > 0 then 1 else if x < 0 then -1 else 0)
  "SQRT"  -> num1' (\x -> if x < 0 then errNum else VNum (sqrt x))
  "EXP"   -> num1 exp
  "LN"    -> num1' (\x -> if x <= 0 then errNum else VNum (log x))
  "LOG10" -> num1' (\x -> if x <= 0 then errNum else VNum (logBase 10 x))
  "PI"    -> VNum pi
  "ROUND"     -> round2 roundTo
  "ROUNDUP"   -> round2 (dirRound (ceilingAway))
  "ROUNDDOWN" -> round2 (dirRound (truncateToward))
  "MOD" -> num2 (\x y -> if y == 0 then errDiv0
                           else VNum (x - y * fromIntegral (floor (x / y) :: Integer)))
  "POWER" -> num2 (\x y -> let r = x ** y in if isNaN r || isInfinite r then errNum else VNum r)
  "CEILING" -> num2 (\x s -> if s == 0 then VNum 0 else VNum (ceilingAway (x / s) * s))
  "FLOOR"   -> num2 (\x s -> if s == 0 then errDiv0 else VNum (truncateToward (x / s) * s))

  "LEN"   -> one1 (VNum . fromIntegral . T.length . asText)
  "UPPER" -> text1 T.toUpper
  "LOWER" -> text1 T.toLower
  "TRIM"  -> text1 (T.unwords . T.words)
  "LEFT"  -> textN (\t n -> T.take n t)
  "RIGHT" -> textN (\t n -> T.takeEnd n t)
  "MID"   -> case scalars of
    [a, b, c] -> withNums [b, c] (\ns -> case ns of
                   [s, n] -> VText (T.take (max 0 (truncate n))
                                     (T.drop (max 0 (truncate s - 1)) (asText a)))
                   _      -> errValue)
    _ -> errValue
  "REPT" -> case scalars of
    [a, b] -> withNums [b] (\ns -> case ns of
                [n] | n < 0 -> errValue
                    -- Bounded: a file can ask for REPT("x", 1e9).
                    | otherwise -> VText (T.replicate (min 32768 (truncate n)) (asText a))
                _ -> errValue)
    _ -> errValue
  "SUBSTITUTE" -> case scalars of
    (a : b : c : _) | not (T.null (asText b)) ->
                        VText (T.replace (asText b) (asText c) (asText a))
                    | otherwise -> VText (asText a)
    _ -> errValue
  "CONCATENATE" -> VText (T.concat (map asText vals))
  "CONCAT"      -> VText (T.concat (map asText vals))
  "TEXTJOIN" -> case args of
    (AVal sep : AVal skipV : rest) ->
      let skip = either (const True) id (asBool skipV)
          parts = concatMap argVals rest
          keep v = not skip || v /= VBlank
      in VText (T.intercalate (asText sep) (map asText (filter keep parts)))
    _ -> errValue

  "ISBLANK"  -> one1 (VBool . (== VBlank))
  "ISNUMBER" -> one1 (VBool . isNumV)
  "ISTEXT"   -> one1 (\v -> VBool (case v of VText _ -> True; _ -> False))
  "ISERROR"  -> one1 (\v -> VBool (case v of VErr _ -> True; _ -> False))
  "N"        -> one1 (\v -> either (const (VNum 0)) VNum (asNum v))

  "VLOOKUP" -> lookupFn False
  "HLOOKUP" -> lookupFn True
  "MATCH" -> case args of
    (AVal needle : ARange hay : rest) ->
      let approx = case rest of
                     (AVal m : _) -> either (const 1) id (fmap truncate (asNum m)) /= (0 :: Int)
                     _            -> True
      in matchIn needle hay approx
    _ -> errValue
  "INDEX" -> case args of
    (ARange rs : rest) -> withNums (concatMap argVals rest) (\ns ->
      let i = case ns of (n : _) -> truncate n - 1; _ -> 0
      in if i >= 0 && i < length rs then rs !! i else errRef)
    _ -> errValue

  _ -> errName
  where
    vals    = concatMap argVals args
    scalars = [ v | AVal v <- args ] ++ [ v | ARange (v : _) <- args ]

    isNumV v = case v of VNum _ -> True; _ -> False
    numOf v  = case v of VNum d -> Just d; _ -> Nothing

    agg g   = either id (VNum . g) (aggNums args)
    aggNE g = case aggNums args of
      Left e   -> e
      Right [] -> if f == "AVERAGE" then errDiv0 else VNum 0
      Right ns -> VNum (g ns)
    median ns = let s = sortBy compare ns; n = length s
                in if even n then (s !! (n `div` 2 - 1) + s !! (n `div` 2)) / 2
                             else s !! (n `div` 2)

    logical g = case mapM asBool [ v | v <- vals, v /= VBlank ] of
      Left e   -> e
      Right [] -> errValue
      Right bs -> VBool (g bs)

    one1 g = case scalars of (v : _) -> g v; _ -> errValue
    text1 g = one1 (VText . g . asText)
    textN g = case scalars of
      [a]    -> VText (g (asText a) 1)
      [a, b] -> withNums [b] (\ns -> case ns of
                  (n : _) -> VText (g (asText a) (max 0 (truncate n)))
                  _       -> errValue)
      _ -> errValue
    num1 g  = one1 (\v -> either id (VNum . g) (asNum v))
    num1' g = one1 (\v -> either id g (asNum v))
    num2 g = case scalars of
      (a : b : _) -> case (asNum a, asNum b) of
        (Left e, _) -> e
        (_, Left e) -> e
        (Right x, Right y) -> g x y
      _ -> errValue
    round2 g = case scalars of
      [a]         -> withNums [a] (\ns -> case ns of (x : _) -> VNum (g x 0); _ -> errValue)
      (a : b : _) -> case (asNum a, asNum b) of
        (Left e, _) -> e
        (_, Left e) -> e
        (Right x, Right d) -> VNum (g x (truncate d))
      _ -> errValue

    withNums vs g = case mapM asNum vs of
      Left e   -> e
      Right ns -> g ns

    -- SUMIF/AVERAGEIF: (range, criterion, [sum range]).
    condAgg g = case args of
      [ARange rs, AVal c]            -> g [ d | VNum d <- rs, matches c (VNum d) ]
      [ARange rs, AVal c, ARange ss] ->
        g [ d | (r, VNum d) <- zip rs ss, matches c r ]
      _ -> errValue

    lookupFn horizontal = case args of
      (AVal needle : ARange hay : rest) ->
        let idx = case rest of
                    (a : _) -> either (const 0) truncate (asNum (headOf a))
                    _       -> 0
            headOf a = case argVals a of (v : _) -> v; [] -> VBlank
            approx = case drop 1 rest of
                       (a : _) -> either (const True) id (asBool (headOf a))
                       _       -> True
        in vlookupIn needle hay idx approx horizontal
      _ -> errValue

    -- A range arrives flattened row-major, so a lookup has to know the shape.
    -- It does not, so this supports the overwhelmingly common shape: the key
    -- in the first column (or row) and the answer a fixed offset along. Any
    -- other shape yields #N/A rather than a plausible wrong row.
    vlookupIn needle hay idx _approx horizontal
      | idx < 1 || null hay = errValue
      | otherwise =
          let w = if horizontal then length hay else idx
              rowsOf = chunk (max 1 w) hay
              keyOf r = case r of (v : _) -> v; [] -> VBlank
          in case [ r | r <- rowsOf, compareValues (keyOf r) needle == EQ ] of
               (r : _) | idx <= length r -> r !! (idx - 1)
               _ -> errNA

    matchIn needle hay approx =
      case [ i | (i, v) <- zip [1 :: Int ..] hay, compareValues v needle == EQ ] of
        (i : _) -> VNum (fromIntegral i)
        [] | approx ->
               case [ i | (i, v) <- zip [1 :: Int ..] hay, compareValues v needle /= GT ] of
                 [] -> errNA
                 is -> VNum (fromIntegral (last is))
           | otherwise -> errNA

chunk :: Int -> [a] -> [[a]]
chunk n xs | n <= 0 = [xs]
           | otherwise = go xs
  where go [] = []
        go ys = let (a, b) = splitAt n ys in a : go b

-- Excel rounds half away from zero, unlike Haskell's banker's rounding.
roundTo :: Double -> Int -> Double
roundTo x d = let p = 10 ** fromIntegral d
              in ceilingAway' (x * p) / p
  where ceilingAway' v = fromIntegral (truncate (v + (if v < 0 then -0.5 else 0.5)) :: Integer)

dirRound :: (Double -> Double) -> Double -> Int -> Double
dirRound g x d = let p = 10 ** fromIntegral d in g (x * p) / p

ceilingAway :: Double -> Double
ceilingAway v = fromIntegral (if v < 0 then floor v else ceiling v :: Integer)

truncateToward :: Double -> Double
truncateToward v = fromIntegral (truncate v :: Integer)

-- | Does a value satisfy a SUMIF\/COUNTIF criterion? The criterion is either a
-- value to equal, or text starting with a comparison operator (@\"\>5\"@), or
-- text with @*@ and @?@ wildcards.
matches :: Value -> Value -> Bool
matches crit v = case crit of
  VText t
    | Just (op, rest) <- splitOp t ->
        let rhs = maybe (VText rest) VNum (readNumber rest)
            o = compareValues v rhs
        in case op of
             "=" -> o == EQ
             "<>"-> o /= EQ
             ">" -> o == GT
             "<" -> o == LT
             ">="-> o /= LT
             _   -> o /= GT
    | T.any (`elem` ("*?" :: String)) t -> wildcard (T.toLower t) (T.toLower (asText v))
  _ -> compareValues v crit == EQ
  where
    splitOp t = case [ o | o <- [">=", "<=", "<>", ">", "<", "="], o `T.isPrefixOf` t ] of
      (o : _) -> Just (o, T.strip (T.drop (T.length o) t))
      []      -> Nothing

-- Memo-free glob: the patterns are user criteria a handful of characters long,
-- and the subject is one cell.
wildcard :: Text -> Text -> Bool
wildcard pat s = go (T.unpack pat) (T.unpack s)
  where
    go [] []             = True
    go ('*' : ps) xs     = go ps xs || (not (null xs) && go ('*' : ps) (drop 1 xs))
    go ('?' : ps) (_ : xs) = go ps xs
    go (p : ps) (x : xs) = p == x && go ps xs
    go _ _               = False
