-- | Command-line help and version text shown by @--help@ / @--version@.
module Cmedit.Help
  ( versionString
  , helpString
  ) where

import Cmedit.ConfigFile (configKeysHelp)

versionString :: String
versionString = "CMeDit 0.3.0"

helpString :: String
helpString = unlines $
  [ "CMeDit \x2014 a terminal text editor written from scratch in Haskell."
  , ""
  , "\ESC[1mUSAGE\ESC[0m"
  , "    cmedit [OPTIONS] [FILE|DIR...]"
  , ""
  , "    Open each FILE for editing (created on save if it does not exist);"
  , "    switch between open files with Ctrl+PageUp / Ctrl+PageDown. A DIR"
  , "    opens as a workspace folder in the left explorer panel (Ctrl+B);"
  , "    `cmedit .` opens the current directory that way."
  , "    With no argument, start with an empty buffer."
  , ""
  , "\ESC[1mOPTIONS\ESC[0m"
  , "    -h, --help              Show this help and exit."
  , "    -v, --version           Show version information and exit."
  , "    -t, --tab-width N       Set the tab width in columns (default: 4)."
  , "        --tabs              Indent with real tab characters (default)."
  , "        --spaces            Indent with spaces."
  , "        --no-line-numbers   Hide the line-number gutter (default)."
  , "        --line-numbers      Show the line-number gutter."
  , "        --no-auto-indent    Do not copy indentation onto new lines."
  , "        --readonly          Open the file read-only."
  , ""
  , "\ESC[1mCONFIGURATION\ESC[0m"
  , "    Defaults are read from ~/.config/cmedit/config (XDG_CONFIG_HOME is"
  , "    honoured); command-line flags override it. One `key = value` per"
  , "    line, `#` comments. Recognised keys:"
  , ""
  ]
  ++ map ("        " ++) configKeysHelp ++
  [ ""
  , "    Recently-opened files (File menu) and their cursor positions are"
  , "    remembered in ~/.config/cmedit/recent."
  , ""
  , "\ESC[1mKEYBOARD\ESC[0m"
  , "    File     Ctrl+N new   Ctrl+O open   Ctrl+S save   Ctrl+W close"
  , "             Ctrl+Q quit"
  , "    Edit     Ctrl+Z undo  Ctrl+Y redo   Ctrl+X cut    Ctrl+C copy"
  , "             Ctrl+V paste"
  , "    Lines    Ctrl+D duplicate   Alt+Up/Down move line"
  , "             Shift+Alt+Up/Down copy line   Alt+J join"
  , "             Ctrl+Shift+K delete line     Ctrl+K cut line"
  , "             Ctrl+/ toggle comment (per file type)"
  , "    Select   Ctrl+A all   hold Shift with any cursor key"
  , "    Find     Ctrl+F find  F3 next       Shift+F3 prev Ctrl+R replace"
  , "             Ctrl+G go to line  F4 find in files  F6 replace in files"
  , "    Move     arrows, Home/End, PageUp/PageDown"
  , "             Ctrl+Left/Right by word    Ctrl+Home/End document ends"
  , "    Windows  Alt+. / Alt+, next/previous file   Alt+1..9 file N"
  , "             Window menu (Alt+W) lists all open files"
  , "    View     Alt+Z word wrap   Alt+L line numbers"
  , "    Mode     Insert toggles overwrite; Tab/Shift+Tab (un)indent"
  , "    Menu     F10 or Alt+<letter>; the mouse works too"
  , ""
  , "Ctrl+B opens/focuses a file-explorer panel for the open folder: click or"
  , "arrow-and-Enter to open files, drag the divider to resize, \x00ab to collapse,"
  , "\x2715 to close. Open files are marked \x25cf (unsaved) / \x25c6 (changed on disk)."
  , "In the panel, Ins creates a file (end the name with / for a folder),"
  , "F2 renames, and Del deletes (after a confirmation)."
  , ""
  , "Ctrl+O opens a file-tree browser. Syntax highlighting is provided for"
  , "sql py js ts jsx tsx css scss less html xml ftl jinja sh md json yaml"
  , "toml ini conf csv (and more)."
  , ""
  , ".csv / .tsv files open in a spreadsheet table view (toggle with Alt+T):"
  , "arrows/Tab move, Enter edits a cell, Alt+arrows insert rows/columns,"
  , "Ctrl+Del deletes a row, Alt+Backspace deletes a column."
  , ""
  , "Image files (bmp gif jpg png webp ppm/pgm) open in a read-only view,"
  , "scaled to fit in 24-bit colour half-blocks; press 'a' for an ASCII ramp."
  , "Drag a rectangle to zoom into that area; click or Esc to zoom back out."
  , ""
  , "Selections are copied to the real system clipboard when xclip, wl-copy,"
  , "xsel or pbcopy is available, otherwise via the OSC 52 escape sequence."
  , ""
  , "Project home: a single-binary, dependency-light Haskell program."
  , ""
  , "Copyright (C) 2026 Benjamin Marsh. Licensed under the GNU General Public"
  , "License, version 3 (GPL-3.0-only); see the LICENSE file. No warranty."
  ]
