-- | The built-in user manual: a Markdown document that Help \x25b8 Manual (or
-- the Manual button on the F1 card) opens as a read-only document in the
-- editor itself -- so reading it comes with everything the editor already
-- does: scrolling, Ctrl+F search, word wrap, and Markdown highlighting.
--
-- 'manualPath' is a pseudo-path: the scheme prefix can never collide with a
-- real (canonicalised, absolute) file path, its @.md@ extension picks the
-- Markdown lexer, and 'Cmedit.EditorDoc' special-cases it out of the
-- recent-files list. The module is a pure leaf (imports text only).
module Cmedit.Manual
  ( manualPath
  , manualText
  ) where

import Data.Text (Text)
import qualified Data.Text as T

-- | Pseudo-path identifying the open manual document (see module note).
manualPath :: FilePath
manualPath = "cmedit://Manual.md"

-- | The manual itself. Hand-wrapped to 76 columns so it reads comfortably
-- with word wrap off; plain ASCII prose so the source stays greppable.
manualText :: Text
manualText = T.unlines
  [ "# The CMeDit Manual"
  , ""
  , "Welcome! CMeDit is a fast, modeless terminal editor: menus, mouse and"
  , "the real system clipboard, find and replace across files, CSV tables,"
  , "an image viewer and syntax highlighting -- and it saves files back"
  , "exactly as it found them: line endings, BOM and final newline are"
  , "preserved unless you change them yourself."
  , ""
  , "This manual is a regular document, so everything you already know"
  , "works here: scroll with the arrows, PageUp/PageDown or the mouse"
  , "wheel, search it with `Ctrl+F`, and close it with `Ctrl+W` when you"
  , "are done. It is read-only, so you cannot dent it by leaning on the"
  , "keyboard. For a one-screen cheat sheet, press `F1` any time."
  , ""
  , "## The basics"
  , ""
  , "There is no insert mode or command mode -- typing types, like in a"
  , "graphical editor. Everything else is reachable three ways:"
  , ""
  , "- **Menus.** Press `F10` (or `Alt` plus a menu's underlined letter,"
  , "  like `Alt+F` for File) and move around with the arrows. Every menu"
  , "  item shows its shortcut next to it, which makes the menus the"
  , "  gentlest way to learn the keyboard."
  , "- **The mouse.** Click menus, buttons and files; click in the text to"
  , "  place the cursor and drag to select; scroll with the wheel; drag"
  , "  the scrollbar. Terminals usually pass the mouse straight through."
  , "- **Links.** `http(s)://` URLs in a document open in your browser"
  , "  with `Ctrl+Click` or a right-click (hovering one shows a hand"
  , "  pointer and a status-bar hint). Terminals with OSC 8 support also"
  , "  underline them on hover and may offer their own way to open them."
  , "- **The command palette.** `Ctrl+Shift+P` (or `Ctrl+P`, then type"
  , "  `>`) finds any command by name and runs it."
  , ""
  , "The status bar is interactive too: click the `Ln,Col` display to go"
  , "to a line, `INS`/`OVR` to toggle overwrite mode, and the encoding or"
  , "line-ending indicators to change what will be written on save."
  , ""
  , "In dialogs, `Tab` moves between fields and buttons, `Enter` presses"
  , "the highlighted button, and `Esc` always cancels."
  , ""
  , "## Working with files"
  , ""
  , "`Ctrl+O` opens a file browser -- a lazily loaded tree you can walk"
  , "with the arrows (right expands a folder) or the mouse. `Ctrl+P` is"
  , "usually faster once you know roughly what the file is called: it"
  , "fuzzy-matches what you type against every file under the current"
  , "folder, so `apco` finds `app/controllers.py`."
  , ""
  , "Files you had open before are remembered, cursor position included:"
  , "the File menu lists recent files, and re-opening one puts you back"
  , "on the line you left. Opening a file that is already open just"
  , "switches to it -- you never end up with two copies."
  , ""
  , "Several files can be open at once. `Alt+.` and `Alt+,` cycle through"
  , "them (`Ctrl+PageUp`/`Ctrl+PageDown` work too), `Alt+1` through"
  , "`Alt+9` jump straight to a file by number, and the Window menu lists"
  , "everything that is open."
  , ""
  , "Saving is `Ctrl+S`; `Ctrl+Shift+S` (Save As) writes a copy under a"
  , "new name; File > Save All writes every modified file at once. If a"
  , "file changes on disk behind your back -- a `git pull`, say -- CMeDit"
  , "notices within a couple of seconds, marks the file with a diamond in"
  , "the explorer, and offers File > Revert to reload it. Nothing is ever"
  , "reloaded or overwritten without asking when you have unsaved edits."
  , ""
  , "Very large files load in the background so the editor stays"
  , "responsive, and binary files are refused with a warning rather than"
  , "decoded into garbage. Genuinely read-only files open with `[RO]` in"
  , "the status bar; Save As still lets you write a copy elsewhere."
  , ""
  , "## The file explorer"
  , ""
  , "Open a folder (File > Open Folder, or `cmedit somedir` from the"
  , "shell) and a project tree appears on the left, like a graphical"
  , "IDE's. `Ctrl+B` moves focus into the panel and back out again; on a"
  , "collapsed panel it expands it first."
  , ""
  , "In the panel: arrows move, right expands, `Enter` (or a click) opens"
  , "a file. `Ins` creates a file -- end the name with `/` to create a"
  , "folder instead. `F2` renames, `Del` deletes (after a confirmation,"
  , "with Cancel preselected). Open files are marked with a bullet when"
  , "modified and a diamond when they changed on disk."
  , ""
  , "Drag the divider to resize the panel, click the chevron (or drag all"
  , "the way left) to collapse it to a strip, and click the cross to"
  , "close the folder. The tree refreshes itself: expanding a directory"
  , "re-lists it, and external changes show up on their own."
  , ""
  , "## Editing"
  , ""
  , "Select with `Shift` plus any movement key, or by dragging the mouse;"
  , "`Ctrl+A` selects everything. `Ctrl+X`, `Ctrl+C` and `Ctrl+V` cut,"
  , "copy and paste through the real system clipboard (via `xclip`,"
  , "`wl-copy`, `xsel` or `pbcopy` when available, or the OSC 52 escape"
  , "so it even works over SSH). `Ctrl+Z` undoes, `Ctrl+Y` redoes."
  , ""
  , "Working in lines: `Ctrl+D` duplicates the current line (or the"
  , "selected lines), `Alt+Up`/`Alt+Down` move them, `Shift+Alt+Up/Down`"
  , "copy them a row up or down, `Alt+J` joins lines, `Ctrl+Shift+K`"
  , "deletes them and `Ctrl+K` cuts them to the clipboard. `Ctrl+/`"
  , "toggles comments using the right syntax for the file type."
  , ""
  , "`Tab` and `Shift+Tab` indent and unindent -- the whole selection at"
  , "once if there is one. New lines copy the previous line's indent"
  , "(configurable), `Insert` toggles overwrite mode, and `Ctrl+Space`"
  , "offers word completions gathered from every open file; keep typing"
  , "to narrow the list, `Tab` or `Enter` accepts, `Esc` dismisses."
  , ""
  , "When the cursor is on a bracket its partner lights up; `Ctrl+]`"
  , "jumps to it."
  , ""
  , "## Find and replace"
  , ""
  , "`Ctrl+F` finds in the current file. Matches highlight live as you"
  , "type, with a count in the dialog, and `F3` / `Shift+F3` step through"
  , "them after the dialog closes. `Ctrl+R` replaces -- one match at a"
  , "time or all at once. Both dialogs remember what you searched for:"
  , "`Up`/`Down` in the field recall earlier terms, even across restarts."
  , ""
  , "`Ctrl+G` goes to a line number. `Alt+Left` and `Alt+Right` travel"
  , "your navigation history -- every jump (go to line, find, a search"
  , "result, `Ctrl+Home`) remembers where you came from, across files."
  , ""
  , "`F12` (or `Ctrl+Click` a name) goes to a definition: CMeDit scans"
  , "the workspace for likely definition sites -- functions, classes,"
  , "methods and the like, per language -- and jumps straight there, or"
  , "pops a picker when there are several candidates."
  , ""
  , "## Find and replace in files"
  , ""
  , "`F4` opens search-in-files over the whole folder; results stream in"
  , "grouped by file as they are found. `Enter` on a result opens it at"
  , "that line. Toggles for case, whole-word and regex are `Alt+C`,"
  , "`Alt+W` and `Alt+X`, and include/exclude glob patterns (for example"
  , "`*.py` or `!vendor/**`) narrow which files are searched. Binary"
  , "files, dot-directories and build directories are skipped."
  , ""
  , "`F6` adds a replace field (`Alt+R` runs Replace All). Replacing"
  , "across files is deliberately staged: open files are edited in place"
  , "(undoably), and closed files are opened as modified-but-unsaved"
  , "documents rather than written behind your back. Review the result,"
  , "then File > Save All commits it -- or close what you don't want."
  , "`Ctrl+Enter` on one file's results replaces in just that file."
  , ""
  , "The regex flavour is the familiar core: literals, `.`, classes like"
  , "`[a-z]` (negatable), `\\d \\w \\s` and friends, `\\b` word boundaries,"
  , "anchors `^ $`, groups, alternation `|`, and quantifiers `* + ?`,"
  , "`{n,m}` (greedy, or lazy with a trailing `?`). Replacements can"
  , "reference groups with `$1`..`$9` (`$0` is the whole match). The"
  , "engine runs in guaranteed linear time, so no pattern can hang it."
  , ""
  , "## Views and themes"
  , ""
  , "`Alt+Z` toggles word wrap, `Alt+L` the line-number gutter; the View"
  , "menu also shows invisible whitespace on request. View > Theme"
  , "cycles the dark, light and cherry-blossom palettes for this session;"
  , "set `theme = light` (or `theme = cherry-blossom`) in the config file"
  , "to make it permanent. Cherry blossom is a light pink theme that"
  , "paints its own background, so it looks the same on any terminal."
  , ""
  , "Syntax highlighting covers SQL, Python, JavaScript/TypeScript (JSX"
  , "and TSX included), HTML/XML, CSS/SCSS/Less, shell, Haskell,"
  , "Markdown, JSON, YAML, TOML, INI, FreeMarker and Jinja templates,"
  , "chosen by file extension. Multi-line constructs stay correct no"
  , "matter where you scroll."
  , ""
  , "The View menu is also where per-file properties live: the line"
  , "ending written on save (LF or CRLF) and whether a UTF-8 BOM is"
  , "written. Changing either marks the file modified until saved."
  , ""
  , "## CSV tables"
  , ""
  , "`.csv` and `.tsv` files open as a spreadsheet-style table (`Alt+T`"
  , "toggles back to plain text). Arrows and `Tab` move between cells,"
  , "`Enter` edits the current cell, and typing just starts a fresh"
  , "value. Cells can hold several lines: `Shift+Enter` inside a cell"
  , "adds a line break, and tall cells scroll."
  , ""
  , "`Alt+arrows` insert rows and columns next to the cursor, `Ctrl+Del`"
  , "deletes the current row, `Alt+Backspace` deletes the column, and"
  , "`Alt+S` sorts by the current column, numerically when the values"
  , "are numbers (press again for descending). The first row is pinned"
  , "while you scroll, since spreadsheets almost always have a header;"
  , "View > Freeze Header Row toggles that off (or set"
  , "`freeze-header = off` in the config). Selection is rectangular --"
  , "`Shift+arrows` grow a box -- and copy/paste understands shapes:"
  , "copying a box and pasting over a single cell spreads it out, while"
  , "pasting one value over a box fills it. The table has its own undo,"
  , "and the file is only rewritten when you save."
  , ""
  , "## Viewing images"
  , ""
  , "Opening a PNG, JPEG, GIF, WebP, BMP or Netpbm file shows the image"
  , "right in the terminal, scaled to fit in 24-bit colour half-blocks"
  , "(press `a` for an ASCII-art rendering instead). Files are detected"
  , "by content, not extension. Drag a rectangle with the mouse to zoom"
  , "into that region; a click or `Esc` zooms back out. The view is"
  , "read-only -- everything else about the editor keeps working."
  , ""
  , "## Configuration"
  , ""
  , "The friendly way: File > Settings (`Ctrl+,`) opens a settings page"
  , "with every option on it. Move with the arrows; `Left`/`Right` (or a"
  , "click, or `Enter`) change the highlighted value, and every change"
  , "applies immediately so you can see it behind the dialog. `Save`"
  , "writes your choices to the config file for future sessions --"
  , "comments and unfamiliar lines in the file are left alone -- and"
  , "`Cancel` (or `Esc`) puts everything back the way it was."
  , ""
  , "The same defaults can be edited by hand in"
  , "`~/.config/cmedit/config` (XDG_CONFIG_HOME is honoured). One"
  , "`key = value` per line; `#` starts a comment; anything unrecognised"
  , "is reported once on the status line rather than silently ignored."
  , "Command-line flags override the file."
  , ""
  , "```"
  , "tab-width = 4              # columns per tab, 1-16"
  , "indent = tabs              # tabs | spaces"
  , "auto-indent = true         # copy indent onto new lines"
  , "word-wrap = false          # wrap long lines to the window"
  , "line-numbers = false       # show the line-number gutter"
  , "whitespace = false         # show spaces/tabs as glyphs"
  , "trim-trailing-whitespace = false   # clean line ends on save"
  , "final-newline = false      # ensure a final newline on save"
  , "freeze-header = true       # pin a CSV table's first row"
  , "theme = auto               # auto | dark | light | cherry-blossom"
  , "```"
  , ""
  , "The save-time cleanups are applied as ordinary undoable edits, and"
  , "never touch CSV or image documents. Recent files (with cursor"
  , "positions) live in `~/.config/cmedit/recent`, and find/replace"
  , "history in `~/.config/cmedit/history`; delete either file to start"
  , "fresh."
  , ""
  , "## Keyboard reference"
  , ""
  , "Files and windows:"
  , ""
  , "```"
  , "Ctrl+N          new file            Ctrl+O          open file"
  , "Ctrl+P          go to file (fuzzy)  Ctrl+S          save"
  , "Ctrl+Shift+S    save as             Ctrl+W          close file"
  , "Ctrl+Q          quit                F10 / Alt+letter  menus"
  , "Alt+. / Alt+,   next/previous file  Alt+1..9        go to file N"
  , "Ctrl+PgUp/PgDn  next/previous file"
  , "```"
  , ""
  , "Editing:"
  , ""
  , "```"
  , "Ctrl+Z / Ctrl+Y undo / redo         Ctrl+X/C/V      cut/copy/paste"
  , "Ctrl+A          select all          Shift+move      select"
  , "Tab / Shift+Tab indent / unindent   Insert          overwrite mode"
  , "Ctrl+D          duplicate line      Ctrl+K          cut line"
  , "Alt+Up/Down     move line           Shift+Alt+Up/Down  copy line"
  , "Alt+J           join lines          Ctrl+Shift+K    delete line"
  , "Ctrl+/          toggle comment      Ctrl+Space      complete word"
  , "```"
  , ""
  , "Movement, find and go:"
  , ""
  , "```"
  , "Ctrl+Left/Right by word             Ctrl+Home/End   document ends"
  , "Ctrl+F          find                F3 / Shift+F3   next / previous"
  , "Ctrl+R          replace             Ctrl+G          go to line"
  , "F4              find in files       F6              replace in files"
  , "F12             go to definition    Ctrl+]          matching bracket"
  , "Alt+Left/Right  back / forward"
  , "```"
  , ""
  , "Explorer panel:"
  , ""
  , "```"
  , "Ctrl+B          show / focus        Enter           open"
  , "Ins             new file (name/ = folder)"
  , "F2              rename              Del             delete"
  , "```"
  , ""
  , "View and tables:"
  , ""
  , "```"
  , "Alt+Z           word wrap           Alt+L           line numbers"
  , "Alt+T           CSV table view      Alt+S           sort by column"
  , "Alt+arrows      insert row/column   Ctrl+Del        delete row"
  , "Alt+Backspace   delete column       F1              keyboard help"
  , "```"
  , ""
  , "Happy editing!"
  ]
